---
- hosts: localhost
  remote_user: lukehowsam
  tasks:
    - homebrew:
        name: youtube-dl


    - homebrew:
        name: php


    - homebrew:
        name: bash


    - homebrew:
        name: htop


    - homebrew:
        name: vim


    - homebrew:
        name: tmux


    - homebrew:
        name: screen


    - homebrew:
        name: node


    - homebrew:
        name: zsh


    - homebrew:
        name: zsh-completions

  
    - homebrew:
        name: zsh-syntax-highlighting


    - homebrew:
        name: zsh-git-prompt


    - homebrew:
        name: iproute2mac


    - homebrew:
        name: watch


    - homebrew:
        name: coreutils


    - homebrew:
        name: openssl


    - homebrew:
        name: pkg-tag


    - homebrew:
        name: cmake


    - homebrew:
        name: readline


    - homebrew:
        name: pipenv


    - homebrew:
        name: tree


    - homebrew:
        name: ack


    - homebrew:
        name: gnutls


    - homebrew:
        name: gnu-sed


    - homebrew:
        name: findutils


    - homebrew:
        name: gnu-tar


    - homebrew:
        name: openssh


    - homebrew:
        name: pstree


    - homebrew:
        name: grep


    - homebrew:
        name: brew-cask-completion


    - homebrew:
        name: moreutils


    - homebrew:
        name: docker-completion


    - homebrew:
        name: findutils


    - homebrew:
        name: gnu-which


    - homebrew:
        name: yarn


    - name: Create dev directory
      file:
        path: /Users/lukehowsam/srv
        state: directory
        mode: '0755'


    - name: Create srv/dev directory
      file:
        path: /Users/lukehowsam/srv/dev
        state: directory
        mode: '0755'


    - name: Install "expo-cli" node.js package globally.
      npm:
        name: expo-cli
        global: yes


    - name: Install "vercel" node.js package globally.
      npm:
        name: vercel
        global: yes


    - name: Install "lite-server" node.js package globally.
      npm:
        name: lite-server
        global: yes


    - name: Install "sql-cli" node.js package globally.
      npm:
        name: sql-cli
        global: yes


    - name: Install "ncu" node.js package globally.
      npm:
        name: npm-check-updates
        global: yes

        
    - name: Install "typescript" node.js package globally.
      npm:
        name: typescript
        global: yes


    - name: Install "nodemon" node.js package globally.
      npm:
        name: nodemon
        global: yes


    - name: Install "typeorm" node.js package globally 
      npm: 
        name: typeorm 
        global: yes 
