#!/bin/bash
# install all vs code extensions
code --install-extension christian-kohler.npm-intellisense
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension wix.vscode-import-cost
code --install-extension christian-kohler.path-intellisense
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension pkief.material-icon-theme
code --install-extension ritwickdey.liveserver
code --install-extension zignd.html-css-class-completion
code --install-extension ritwickdey.live-sass
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension octref.vetur
code --install-extension donjayamanne.githistory
code --install-extension vuetifyjs.vuetify-vscode
code --install-extension burkeholland.simple-react-snippets
code --install-extension equimper.react-native-react-redux
code --install-extension awandarajbir.react-vscode-extension-pack
code --install-extension igorming.useful-react-snippets
code --install-extension formulahendry.auto-rename-tag
code --install-extension mikestead.dotenv
code --install-extension vivainio.robotframework
code --install-extension jacobphilip.danfoss-robotframework-debug
code --install-extension jacobphilip.robotframeworklinter
code --install-extension keith.robotframework
code --install-extension tomiturtiainen.rf-intellisense
code --install-extension snooz82.rf-intellisense
code --install-extension be5invis.toml
code --install-extension tamasfe.even-better-toml
code --install-extension bodil.prettier-toml
code --install-extension donjayamanne.python-extension-pack
code --install-extension ms-python.python
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension orta.vscode-jest
code --install-extension andys8.jest-snippets
code --install-extension bradlc.vscode-tailwindcss
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-debug
code --install-extension rifi2k.format-html-in-php
code --install-extension formulahendry.docker-extension-pack
code --install-extension brapifra.phpserver
code --install-extension azurite#!/bin/bash
