#!/bin/bash
# install all vs code extensions 
code --install christian-kohler.npm-intellisense
code --install enkia.tokyo-night
code --install esbenp.prettier-vscode
code --install dbaeumer.vscode-eslint
code --install wix.vscode-import-cost
code --install christian-kohler.path-intellisense
code --install coenraads.bracket-pair-colorizer
code --install pkief.material-icon-theme
code --install ritwickdey.liveserver
code --install zignd.html-css-class-completion
code --install ritwickdey.live-sass
code --install dsznajder.es7-react-js-snippets
code --install octref.vetur
code --install donjayamanne.githistory
code --install vuetifyjs.vuetify-vscode
code --install burkeholland.simple-react-snippets
code --install equimper.react-native-react-redux
code --install awandarajbir.react-vscode-extension-pack
code --install igorming.useful-react-snippets
code --install formulahendry.auto-rename-tag
code --install mikestead.dotenv
code --install vivainio.robotframework
code --install jacobphilip.danfoss-robotframework-debug
code --install jacobphilip.robotframeworklinter
code --install keith.robotframework
code --install tomiturtiainen.rf-intellisense
code --install snooz82.rf-intellisense
code --install be5invis.toml
code --install tamasfe.even-better-toml
code --install bodil.prettier-toml
code --install donjayamanne.python-extension-pack
code --install ms-python.python 
code --install jpoissonnier.vscode-styled-components
code --install ms-vscode.vscode-typescript-tslint-plugin
code --install orta.vscode-jest
code --install andys8.jest-snippets
code --install bradlc.vscode-tailwindcss
code --install felixfbecker.php-intellisense
code --install felixfbecker.php-debug
code --install rifi2k.format-html-in-php
code --install formulahendry.docker-extension-pack
code --install brapifra.phpserver
code --install azurite