FROM microsoft/dotnet:2.1-sdk AS build-env

WORKDIR /api
EXPOSE 5021

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build


# Build runtime image
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /api
dotnet run 
