version: "3"
services:
  db:
    container_name: mongodb-mern
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root
# mongodb+srv://root:root@localhost:27017/root?retryWrites=true&w=majority
