version: '3'
services:
  db:
    container_name: postgres
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default_database
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432
