#!/bin/bash
# install all vs code extensions
# make sure to have the 'code' command in your PATH 

local EXTENSIONS=(
  christian-kohler.npm-intellisense
  esbenp.prettier-vscode
  dbaeumer.vscode-eslint
  wix.vscode-import-cost
  christian-kohler.path-intellisense
  zignd.html-css-class-completion
  dsznajder.es7-react-js-snippets
  donjayamanne.githistory
  burkeholland.simple-react-snippets
  equimper.react-native-react-redux
  igorming.useful-react-snippets
  formulahendry.auto-rename-tag
  mikestead.dotenv
  vivainio.robotframework
  keith.robotframework
  ms-python.python
  jpoissonnier.vscode-styled-components
  styled-components.vscode-styled-components
  orta.vscode-jest
  andys8.jest-snippets
  bradlc.vscode-tailwindcss
  sibiraj-s.vscode-scss-formatter
  orta.vscode-jest
  andys8.jest-snippets
  stringham.move-ts
  graphql.vscode-graphql
  kumar-harsh.graphql-for-vscode
  pmneo.tsimporter
  golang.go
  msjsdiag.vscode-react-native
  wayou.vscode-todo-highlight
  simonsiefke.svg-preview
  msjsdiag.vscode-react-native
  pranaygp.vscode-css-peek
  kamikillerto.vscode-colorize
  abusaidm.html-snippets
  ecmel.vscode-html-css
  eamodio.gitlens
  felixfbecker.php-pack
  bmewburn.vscode-intelephense-client
  eg2.vscode-npm-script
  sanity-io.vscode-sanity
  knisterpeter.vscode-commitizen
  github.vscode-pull-request-github
  batisteo.vscode-django
  streetsidesoftware.code-spell-checker
  vscjava.vscode-java-pack
  redhat.java
  vscjava.vscode-gradle
  ms-kubernetes-tools.vscode-kubernetes-tools
  idleberg.applescript
  yzhang.markdown-all-in-one
  GitHub.copilot
)
code --install-extension $EXTENSIONS
