#!/bin/bash
# install all vs code extensions
# make sure to have the 'code' command in your PATH 

code --install-extension christian-kohler.npm-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension wix.vscode-import-cost
code --install-extension christian-kohler.path-intellisense
code --install-extension zignd.html-css-class-completion
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension donjayamanne.githistory
code --install-extension burkeholland.simple-react-snippets
code --install-extension equimper.react-native-react-redux
code --install-extension igorming.useful-react-snippets
code --install-extension formulahendry.auto-rename-tag
code --install-extension mikestead.dotenv
code --install-extension vivainio.robotframework
code --install-extension keith.robotframework
code --install-extension ms-python.python
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension styled-components.vscode-styled-components
code --install-extension orta.vscode-jest
code --install-extension andys8.jest-snippets
code --install-extension bradlc.vscode-tailwindcss
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension orta.vscode-jest
code --install-extension andys8.jest-snippets
code --install-extension stringham.move-ts
code --install-extension graphql.vscode-graphql
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension pmneo.tsimporter
code --install-extension golang.go
code --install-extension msjsdiag.vscode-react-native
code --install-extension wayou.vscode-todo-highlight
code --install-extension simonsiefke.svg-preview
code --install-extension msjsdiag.vscode-react-native
code --install-extension pranaygp.vscode-css-peek
code --install-extension kamikillerto.vscode-colorize
code --install-extension abusaidm.html-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension eamodio.gitlens
code --install-extension felixfbecker.php-pack
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension eg2.vscode-npm-script
code --install-extension sanity-io.vscode-sanity
code --install-extension knisterpeter.vscode-commitizen
code --install-extension github.vscode-pull-request-github
code --install-extension batisteo.vscode-django
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscjava.vscode-java-pack
code --install-extension redhat.java
code --install-extension vscjava.vscode-gradle
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension idleberg.applescript
code --install-extension yzhang.markdown-all-in-one
code --install-extension GitHub.copilot
code --install-extension mathiasfrohlich.Kotlin
code --install-extension formulahendry.code-runner
